---
title: "Introduction_to_R"
author: "Meg Hemmerlein"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Helpful Keys

# Play button = run whole chunk

# Cmd + Enter = run one line of code

```{r Variables -- Hello world}
"Hello world"

message = "Hello world"

print(message)

message

ls()
```

```{r Variables -- Data Types}

species = c("Adelie", "Gentoo", "Chinstrap")
island = as.factor(c("Torgersen", "Biscoe", "Dream"))
body_mass_g = as.numeric(c(4987, 5850, 3575))

class(species)
class(island)
class(body_mass_g)

penguins <- data.frame(
  species,
  island,
  body_mass_g)

str(penguins)
```

```{r Installing packages}

#install.packages("tidyverse")
#install.packages("readr")

library(tidyverse)
library(readr)
```

```{r Reading in a file}

getwd()

penguins = read_csv("/Users/MegHemmerlein/Library/CloudStorage/OneDrive-Colostate/MtBlueSky-Workshop/Workshop-Sessions/Introduction-to-Coding/penguins.csv")

```

```{r Explore file}

str(penguins)

ncol(penguins)
nrow(penguins)

colnames(penguins)
```

```{r Plotting}

#install.packages("ggplot2")

library(ggplot2)

ggplot(data = penguins, aes(x = bill_length_mm, y = bill_depth_mm)) +
  geom_point(aes(color = species, 
                 shape = species),
             size = 2)

ggplot(data = penguins, aes(x = bill_length_mm, y = bill_depth_mm)) +
  geom_point(aes(color = species, 
                 shape = species),
             size = 2) +
    scale_color_manual(values = c("darkorange","darkorchid","cyan4"))


ggplot(data = penguins, aes(x = bill_length_mm, y = bill_depth_mm)) +
  geom_point(aes(color = species, 
                 shape = species),
             size = 2) + 
  geom_smooth(method = "lm", se = FALSE, aes(color = species)) +
  scale_color_manual(values = c("darkorange","darkorchid","cyan4"))

```


```{r Extra problems}

#1) Simpson's paradox is a statistical phenomenon where a trend between two variables appears in seperate groups of data, but disappears or reverses when groups are combined. Can you omit the grouping by species and plot bill length by bill depth to show this phenomenon? 

#2) Are there differnces in the distribution of flipper length across the three species? Hint: look into a function called 'geom_histogram'.

#3) Can you represent this same data as a box blot instead? Hint: X axis will be species and y axis will be flipper length. Hint 2: look into function called 'geom_boxplot'.

```

